version: '3'
services:
  drupal:
    image: drupal:latest
    networks:
      - drupal
    ports:
      - "80:80"
    links:
      - postgres:postgres
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    networks:
      - drupal
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
networks:
  drupal:
    ipam:
      driver: default
